## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -254.0
accel_x_max: 254.0
accel_y_min: -250.0
accel_y_max: 256.0
accel_z_min: -266.0
accel_z_max: 248

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [215.598, 216.910, 114.360]
magn_ellipsoid_transform: [[0.991797, -0.00429089, 0.0123735], [-0.00429089, 0.983224, -0.00718378], [0.0123735, -0.00718378, 0.968501]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.01
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.03
